### ISSUE TITLE
HTTPS 

### ISSUE THREAD

**Issue by GonzaloRizzo** [johnblanco/predictor_electoral#20]
Como estas haciendo el Deploy? Capaz estaria bueno que metas Caddy que te da un certificado de Let's Encrypt gratuito.
Cualquier cosa te ayudo

**Comment by johnblanco** [comment]
Me encantaria, cualquier cosa que aumente la transparencia es bienvenida. Haces un PR?

**Comment by mixedCase** [comment]
@johnblanco Si podés contarnos un poco más en qué lo tenés hosteado yo me ofrezco también a hacer un script de deployment que incluya Caddy. Es una especie de VPS como los droplets de DigitalOcean/EC2 de Amazon u otra cosa?

**Comment by johnblanco** [comment]
Esta hosteado en pythonanywhere, podes hacerte una cuenta gratis y probarlo.

**Comment by mixedCase** [comment]
En ese caso no podríamos meterle Caddy (al menos no sin hacks), pero por suerte en pythonanywhere te ofrecen este mismo servicio gratis si lo activás en el panel:

https://help.pythonanywhere.com/pages/HTTPSSetup

**Comment by johnblanco** [comment]
Listo. ahora es https, ven necesario hacer algo mas?

**Comment by dirkgentle** [comment]
Yo acabo de entrar y se ve como HTTPS.

**Comment by mixedCase** [comment]
Por algún motivo la redirección de https://aquienvoto.uy a https://www.aquienvoto.uy no parece andar (mientras que por HTTP sí). Pero fuera de eso, quedó perfecto :clap:

**Comment by GonzaloRizzo** [comment]
Y si lo dejamos sin www? Se está dejando de usar ya

**Comment by johnblanco** [comment]
Esta funcionando de las 2 formas ahora. Saludos
